### ISSUE TITLE
ModuleNotFoundError: No module named 'zenml.integrations.sklearn.helpers'

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenbytes#16]
I am facing the issue while importing the below code:
from zenml.integrations.sklearn.helpers.digits import get_digits

Error:
ModuleNotFoundError: No module named 'zenml.integrations.sklearn.helpers'

**Comment by dnth** [comment]
Hi @Coder-Vishali which version of zenml are you running on?

**Comment by fa9r** [comment]
@Coder-Vishali thanks for opening the issue. I removed this function from ZenML core during the last release, but apparently forgot to adjust ZenBytes accordingly. I'll make sure to fix this later today.

To temporarily fix this, you can either downgrade zenml to the previous version, or you can replace the `get_digits()` call with the following code:

```
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
data = digits.images.reshape((len(digits.images), -1))
X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.2, shuffle=False
)
```

**Comment by fa9r** [comment]
@Coder-Vishali I just updated ZenBytes, all lessons should now work correctly with the latest zenml version 0.13.0.

Please let me know if that fixed the issue for you.

Best,
Felix

**Comment by Coder-Vishali** [comment]
> Hi @Coder-Vishali which version of zenml are you running on?

I am using 0.13.0 version of zenml

**Comment by Coder-Vishali** [comment]
> @Coder-Vishali thanks for opening the issue. I removed this function from ZenML core during the last release, but apparently forgot to adjust ZenBytes accordingly. I'll make sure to fix this later today.
> 
> To temporarily fix this, you can either downgrade zenml to the previous version, or you can replace the `get_digits()` call with the following code:
> 
> ```
> from sklearn.datasets import load_digits
> from sklearn.model_selection import train_test_split
> 
> digits = load_digits()
> data = digits.images.reshape((len(digits.images), -1))
> X_train, X_test, y_train, y_test = train_test_split(
>     data, digits.target, test_size=0.2, shuffle=False
> )
> ```

Hey Thanks for the quick reply. It is working fine now!

**Comment by Coder-Vishali** [comment]
> @Coder-Vishali I just updated ZenBytes, all lessons should now work correctly with the latest zenml version 0.13.0.
> 
> Please let me know if that fixed the issue for you.
> 
> Best, Felix

Issue is fixed now!
